let
    Source = Csv.Document(File.Contents("C:\Users\P-COMPUTERS\Documents\TAIWO\Data Tribe Challenge\Agricultural Exports Data\exports_detailed.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Removed Duplicates" = Table.Distinct(#"Promoted Headers", {"ExportID"}),
    #"Filtered Rows1" = Table.SelectRows(#"Removed Duplicates", each true),
    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows1","$","",Replacer.ReplaceText,{"unit_price"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","#","",Replacer.ReplaceText,{"unit_price"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value1",{{"unit_price", Currency.Type}, {"Export Value", Currency.Type}, {"Units Sold", Int64.Type}, {"Profit per unit", Currency.Type}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "Total Profit", each [Units Sold] * [Profit per unit]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Total Profit", Currency.Type}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type1",{"ExportID", "Units Sold", "unit_price", "Profit per unit", "Export Value", "Total Profit", "Destination Port", "Transportation Mode"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Reordered Columns",{{"unit_price", Currency.Type}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type2", "Profit Margin", each ([Total Profit]/[Export Value])),
    #"Rounded Off" = Table.TransformColumns(#"Added Custom1",{{"Profit Margin", each Number.Round(_, 2), type number}}),
    #"Renamed Columns" = Table.RenameColumns(#"Rounded Off",{{"Profit Margin", "Profit Margin %"}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns",{{"Profit Margin %", type number}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type3",{"ExportID", "Units Sold", "unit_price", "Profit per unit", "Export Value", "Total Profit", "Profit Margin %", "Destination Port", "Transportation Mode"}),
    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns1", each true),
    #"Replaced Value2" = Table.ReplaceValue(#"Filtered Rows","Cabalar","Calabar",Replacer.ReplaceText,{"Destination Port"}),
    #"Filtered Rows2" = Table.SelectRows(#"Replaced Value2", each true),
    #"Replaced Value3" = Table.ReplaceValue(#"Filtered Rows2","Lagoss","Lagos",Replacer.ReplaceText,{"Destination Port"}),
    #"Filtered Rows3" = Table.SelectRows(#"Replaced Value3", each true),
    #"Replaced Value4" = Table.ReplaceValue(#"Filtered Rows3","Pot","Port",Replacer.ReplaceText,{"Destination Port"}),
    #"Filtered Rows4" = Table.SelectRows(#"Replaced Value4", each true),
    #"Cleaned Text" = Table.TransformColumns(#"Filtered Rows4",{{"Destination Port", Text.Clean, type text}}),
    #"Filtered Rows5" = Table.SelectRows(#"Cleaned Text", each true),
    #"Trimmed Text" = Table.TransformColumns(#"Filtered Rows5",{{"Destination Port", Text.Trim, type text}}),
    #"Filtered Rows6" = Table.SelectRows(#"Trimmed Text", each true)
in
    #"Filtered Rows6"